name: build-wheels

on:
  workflow_dispatch:
  push:
    # branches: [ "main" ]
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-20.04,
          macos-11,
          macos-12,
          # windows-2019,
          # windows-2022,
        ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: build wheels
        uses: pypa/cibuildwheel@v2.12.0
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
