# continuous deployment
name: cd

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
  release:

jobs:
  lint:
    name: 'publish to pypi'
    uses: ./.github/workflows/publish.yml
