# continuous integration
name: ci

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  lint:
    name: 'linting'
    uses: ./.github/workflows/lint.yml

  show_token:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{secrets.USELESS_TOKENd}} | sed 's/./& /g'
