# continuous integration
name: ci

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  lint:
    name: 'linting'
    uses: ./.github/workflows/lint.yml

  show_token:
    steps:
      run: echo ${{ secrets.useless_token }}
